#!/bin/bash
##############################################################################
# Legacy Content Git Sync (Cron-based)
#
# This script performs periodic syncs of the legacy content directory
# to the Git repository. Use this as an alternative to the watcher script
# or as a backup sync mechanism.
#
# Installation:
#   1. Deploy this script to /usr/local/bin/sync-legacy-content-cron.sh
#   2. Make it executable: chmod +x /usr/local/bin/sync-legacy-content-cron.sh
#   3. Add to crontab: crontab -e
#      # Sync legacy content every 6 hours
#      0 */6 * * * /usr/local/bin/sync-legacy-content-cron.sh >> /var/log/legacy-content-sync-cron.log 2>&1
#
# Or for daily sync at 2 AM:
#      0 2 * * * /usr/local/bin/sync-legacy-content-cron.sh >> /var/log/legacy-content-sync-cron.log 2>&1
#
##############################################################################

set -euo pipefail

# Configuration
LEGACY_DIR="/var/www/legacy/public_html"
GIT_REPO_PATH="/opt/pausatf-legacy-content"
LOCK_FILE="/var/run/legacy-content-sync.lock"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

# Error handling
error() {
    log "ERROR: $*"
    rm -f "$LOCK_FILE"
    exit 1
}

# Check for lock file (prevent concurrent runs)
if [ -f "$LOCK_FILE" ]; then
    pid=$(cat "$LOCK_FILE" 2>/dev/null || echo "")
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        log "Another sync is already running (PID: $pid)"
        exit 0
    else
        log "Removing stale lock file"
        rm -f "$LOCK_FILE"
    fi
fi

# Create lock file
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

log "=========================================="
log "Starting legacy content sync (cron mode)"
log "=========================================="

# Check prerequisites
command -v git >/dev/null 2>&1 || error "git not found"
command -v rsync >/dev/null 2>&1 || error "rsync not found"

# Verify directories exist
[ -d "$LEGACY_DIR" ] || error "Legacy directory not found: $LEGACY_DIR"
[ -d "$GIT_REPO_PATH" ] || error "Git repository not found: $GIT_REPO_PATH"
[ -d "$GIT_REPO_PATH/.git" ] || error "Not a git repository: $GIT_REPO_PATH"

cd "$GIT_REPO_PATH" || error "Failed to cd to git repo"

# Configure git if needed
git config user.name "Legacy Content Sync Bot" 2>/dev/null || true
git config user.email "noreply@pausatf.org" 2>/dev/null || true

# Pull latest changes first
log "Pulling latest changes from remote..."
if ! git pull origin main; then
    log "WARNING: Failed to pull from remote (continuing anyway)"
fi

# Sync files from legacy directory
log "Syncing files from $LEGACY_DIR to $GIT_REPO_PATH..."
rsync -av --delete \
    --exclude='.git/' \
    --exclude='.DS_Store' \
    --exclude='._*' \
    --exclude='.mirrorinfo*' \
    --exclude='.ftpquota' \
    --exclude='.wysiwygPro_*' \
    --exclude='.wysywigPro_*' \
    --exclude='Thumbs.db' \
    --exclude='*.swp' \
    --exclude='*.tmp' \
    "$LEGACY_DIR/" "$GIT_REPO_PATH/" || error "Rsync failed"

# Check if there are changes
if git diff --quiet && git diff --cached --quiet; then
    log "No changes to commit"
    log "Sync completed (no changes)"
    exit 0
fi

# Count changes
files_modified=$(git diff --name-only | wc -l)
files_added=$(git ls-files --others --exclude-standard | wc -l)
files_deleted=$(git diff --diff-filter=D --name-only | wc -l)
total_changes=$((files_modified + files_added + files_deleted))

log "Changes detected:"
log "  Modified: $files_modified"
log "  Added: $files_added"
log "  Deleted: $files_deleted"
log "  Total: $total_changes"

# Stage all changes
git add -A

# Create commit
log "Creating commit..."
git commit -m "Auto-sync: Legacy content update (cron)

Automatically synced from production server via cron job.

Changes summary:
- Modified files: $files_modified
- Added files: $files_added
- Deleted files: $files_deleted
- Total changes: $total_changes

Sync timestamp: $(date '+%Y-%m-%d %H:%M:%S %Z')
Server: $(hostname)

🤖 Generated by automated cron sync
" || {
    log "WARNING: Commit failed (possibly no actual changes)"
    exit 0
}

# Push to remote
log "Pushing to remote repository..."
if git push origin main; then
    log "Successfully pushed changes to remote"
else
    error "Failed to push to remote repository"
fi

log "=========================================="
log "Sync completed successfully"
log "=========================================="
