---
argument_specs:
  main:
    short_description: Common system configuration
    options:
      timezone:
        type: str
        default: America/Los_Angeles
        description: System timezone
      allowed_ssh_networks:
        type: list
        elements: str
        default: []
        description: CIDR networks allowed SSH access
