---
- name: Assert Apache variables are defined
  ansible.builtin.assert:
    that:
      - apache_server_name is defined
      - apache_server_name | length > 0
    fail_msg: "apache_server_name must be defined"
    quiet: true
