---
argument_specs:
  main:
    short_description: WordPress management role
    options:
      wp_site:
        type: dict
        required: true
        description: WordPress site configuration dict
      wpcli_path:
        type: str
        default: /usr/local/bin/wp
        description: Path to WP-CLI binary
      wp_users:
        type: list
        elements: dict
        default: []
        description: Authorized WordPress user list
      wp_users_remove:
        type: list
        elements: dict
        default: []
        description: WordPress users to remove
