#!/bin/bash
##############################################################################
# Legacy Content Git Sync Watcher
#
# This script watches the legacy content directory for changes and
# automatically syncs them to the Git repository.
#
# Installation:
#   1. Deploy this script to /usr/local/bin/sync-legacy-content-watcher.sh
#   2. Install inotify-tools: apt-get install inotify-tools
#   3. Create systemd service (see sync-legacy-content-watcher.service)
#   4. Configure GIT_REPO_PATH to point to a clone of the repository
#
# Usage:
#   ./sync-legacy-content-watcher.sh
#
##############################################################################

set -euo pipefail

# Configuration
LEGACY_DIR="/var/www/legacy/public_html"
GIT_REPO_PATH="/opt/pausatf-legacy-content"
EXCLUDE_PATTERNS="(.DS_Store|.mirrorinfo|.ftpquota|.wysiwygPro_.*|Thumbs.db|._.*)"
LOG_FILE="/var/log/legacy-content-sync.log"
DEBOUNCE_SECONDS=30  # Wait 30 seconds after last change before syncing

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Error handling
error() {
    log "ERROR: $*"
    exit 1
}

# Check prerequisites
command -v inotifywait >/dev/null 2>&1 || error "inotifywait not found. Install inotify-tools: apt-get install inotify-tools"
command -v git >/dev/null 2>&1 || error "git not found"

# Verify directories exist
[ -d "$LEGACY_DIR" ] || error "Legacy directory not found: $LEGACY_DIR"
[ -d "$GIT_REPO_PATH" ] || error "Git repository not found: $GIT_REPO_PATH"
[ -d "$GIT_REPO_PATH/.git" ] || error "Not a git repository: $GIT_REPO_PATH"

log "Starting legacy content watcher"
log "Watching: $LEGACY_DIR"
log "Git repo: $GIT_REPO_PATH"

# Sync function
sync_to_git() {
    log "Starting sync..."

    cd "$GIT_REPO_PATH" || error "Failed to cd to git repo"

    # Pull latest changes first
    log "Pulling latest changes from remote..."
    git pull origin main || log "WARNING: Failed to pull from remote (continuing anyway)"

    # Sync files from legacy directory
    log "Syncing files from $LEGACY_DIR..."
    rsync -av --delete \
        --exclude='.git/' \
        --exclude='.DS_Store' \
        --exclude='._*' \
        --exclude='.mirrorinfo*' \
        --exclude='.ftpquota' \
        --exclude='.wysiwygPro_*' \
        --exclude='Thumbs.db' \
        "$LEGACY_DIR/" "$GIT_REPO_PATH/" || error "Rsync failed"

    # Check if there are changes
    if git diff --quiet && git diff --cached --quiet; then
        log "No changes to commit"
        return 0
    fi

    # Stage all changes
    git add -A

    # Create commit
    local changed_files
    changed_files=$(git diff --cached --name-only | wc -l)

    log "Committing $changed_files changed files..."
    git commit -m "Auto-sync: Legacy content update

Automatically synced from production server.

Changed files: $changed_files
Timestamp: $(date '+%Y-%m-%d %H:%M:%S')

🤖 Generated by automated sync watcher
" || log "WARNING: Commit failed (possibly no changes)"

    # Push to remote
    log "Pushing to remote..."
    git push origin main || error "Failed to push to remote"

    log "Sync completed successfully"
}

# Debounce mechanism
last_change_time=0

while true; do
    # Wait for file system events
    inotifywait -r -e modify,create,delete,move \
        --exclude "$EXCLUDE_PATTERNS" \
        "$LEGACY_DIR" 2>/dev/null

    # Record time of change
    current_time=$(date +%s)
    last_change_time=$current_time

    log "Detected changes, waiting for quiet period (${DEBOUNCE_SECONDS}s)..."

    # Wait for debounce period
    sleep "$DEBOUNCE_SECONDS"

    # Check if more changes occurred during wait
    if [ "$last_change_time" -eq "$current_time" ]; then
        # No more changes, safe to sync
        sync_to_git
    else
        log "More changes detected during debounce, extending wait..."
    fi
done
