---
# Apache handlers

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  listen: "apache changed"

- name: Reload Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  listen: "apache changed"

- name: Start Apache
  ansible.builtin.service:
    name: apache2
    state: started
