---
php_version: "8.3"
php_memory_limit: "256M"
php_max_execution_time: 300
php_max_input_time: 300
php_max_input_vars: 3000
php_upload_max_filesize: "64M"
php_post_max_size: "64M"
php_date_timezone: "UTC"
php_opcache_enable: 1
php_opcache_memory_consumption: 128
php_opcache_interned_strings_buffer: 16
php_opcache_max_accelerated_files: 10000
php_opcache_revalidate_freq: 2
php_opcache_save_comments: 1
php_modules:
  - bcmath
  - cli
  - common
  - curl
  - gd
  - imagick
  - mbstring
  - mysql
  - opcache
  - soap
  - xml
  - zip
