---
galaxy_info:
  author: pausatf
  role_name: backup_wordpress
  description: WordPress backup with disk guard and DO Spaces offload
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
