---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when: fail2ban_manage_service | bool

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: fail2ban_manage_service | bool

- name: Reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
  when: fail2ban_manage_service | bool
