---
galaxy_info:
  role_name: redis
  namespace: pausatf
  author: pausatf
  description: "Redis server installation and configuration"
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: common
