---
galaxy_info:
  author: pausatf
  description: "Monitoring and backup for PAUSATF infrastructure"
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies: []
