---
# PHP handlers

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart PHP-FPM
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
  failed_when: false
