---
- name: Restart web server
  ansible.builtin.systemd:
    name: "{{ 'apache2' if web_server | default('apache') == 'apache' else 'lsws' }}"
    state: restarted

- name: Reload web server
  ansible.builtin.systemd:
    name: "{{ 'apache2' if web_server | default('apache') == 'apache' else 'lsws' }}"
    state: reloaded

- name: Restart PHP-FPM
  ansible.builtin.systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted
  when: use_php_fpm | default(false)
