---
argument_specs:
  main:
    short_description: Apache web server role
    options:
      apache_mpm:
        type: str
        default: event
        choices: [event, prefork, worker]
        description: Apache MPM module
      apache_listen_port:
        type: int
        default: 80
        description: HTTP listen port
      apache_server_name:
        type: str
        required: true
        description: Primary server name
