---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: wordpress

  post_tasks:
    - name: Ensure OpenLiteSpeed is started for tests
      service:
        name: lsws
        state: started

    - name: Ensure LSPHP-FPM is started for tests
      service:
        name: lsphp83-fpm
        state: started
