---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check WP-CLI is installed
      ansible.builtin.stat:
        path: /usr/local/bin/wp
      register: wpcli_stat
      failed_when: not wpcli_stat.stat.exists

    - name: Check WordPress path exists
      ansible.builtin.stat:
        path: /var/www/html
      register: wp_dir
      failed_when: not wp_dir.stat.isdir

    - name: Check WordPress .htaccess exists
      ansible.builtin.stat:
        path: /var/www/html/.htaccess
      register: htaccess_stat
      failed_when: not htaccess_stat.stat.exists

    - name: Check uploads directory exists
      ansible.builtin.stat:
        path: /var/www/html/wp-content/uploads
      register: uploads_dir
      failed_when: not uploads_dir.stat.isdir

    - name: Check uploads .htaccess blocks PHP execution
      ansible.builtin.stat:
        path: /var/www/html/wp-content/uploads/.htaccess
      register: uploads_htaccess
      failed_when: not uploads_htaccess.stat.exists
