---
# New Relic handlers

- name: Restart New Relic infrastructure
  ansible.builtin.service:
    name: newrelic-infra
    state: restarted

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart PHP-FPM
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
