#!/usr/bin/env bash
set -euo pipefail

# Populate Ansible vault with managed DB credentials from DigitalOcean.
#
# Prerequisites:
#   1. DIGITALOCEAN_TOKEN env var set
#   2. doctl installed
#   3. ansible-vault password configured
#   4. Production managed MySQL cluster exists (via terraform apply)
#
# Usage:
#   ./scripts/setup-managed-db-vars.sh [production|staging]

ENVIRONMENT="${1:-production}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VAULT_DIR="$REPO_ROOT/ansible/group_vars/$ENVIRONMENT"

# --- Preflight checks ---

if [[ -z "${DIGITALOCEAN_TOKEN:-}" ]]; then
  echo "ERROR: DIGITALOCEAN_TOKEN is not set." >&2
  exit 1
fi

if ! command -v doctl &>/dev/null; then
  echo "ERROR: doctl is not installed. Run: brew install doctl" >&2
  exit 1
fi

if ! command -v ansible-vault &>/dev/null; then
  echo "ERROR: ansible-vault is not installed." >&2
  exit 1
fi

# --- Find the managed DB cluster ---

echo "Looking for $ENVIRONMENT database cluster..."

CLUSTER_NAME=""
case "$ENVIRONMENT" in
  production) CLUSTER_NAME="pausatf-prod-db" ;;
  staging)    CLUSTER_NAME="pausatf-stage-db" ;;
  *)
    echo "ERROR: Unknown environment '$ENVIRONMENT'. Use 'production' or 'staging'." >&2
    exit 1
    ;;
esac

CLUSTER_ID=$(doctl databases list --format ID,Name --no-header -t "$DIGITALOCEAN_TOKEN" \
  | grep "$CLUSTER_NAME" | awk '{print $1}')

if [[ -z "$CLUSTER_ID" ]]; then
  echo "ERROR: No database cluster matching '$CLUSTER_NAME' found." >&2
  echo "Available clusters:" >&2
  doctl databases list --format ID,Name,Engine,Status -t "$DIGITALOCEAN_TOKEN" >&2
  exit 1
fi

echo "Found cluster: $CLUSTER_ID ($CLUSTER_NAME)"

# --- Fetch credentials ---

echo "Fetching connection details..."

DB_INFO=$(doctl databases connection "$CLUSTER_ID" --format Host,Port,User,Password,Database \
  --no-header -t "$DIGITALOCEAN_TOKEN")

DB_HOST=$(echo "$DB_INFO" | awk '{print $1}')
DB_PORT=$(echo "$DB_INFO" | awk '{print $2}')
DB_USER=$(echo "$DB_INFO" | awk '{print $3}')
DB_PASS=$(echo "$DB_INFO" | awk '{print $4}')

echo "  Host: $DB_HOST"
echo "  Port: $DB_PORT"
echo "  User: $DB_USER"
echo "  Pass: ***${DB_PASS: -4}"

# --- Write vault file ---

mkdir -p "$VAULT_DIR"

VAULT_FILE="$VAULT_DIR/vault.yml"
VAULT_CONTENT="---
# Managed database credentials (from DigitalOcean)
# Auto-generated by scripts/setup-managed-db-vars.sh
vault_managed_db_host: \"$DB_HOST\"
vault_managed_db_user: \"$DB_USER\"
vault_managed_db_password: \"$DB_PASS\"
"

if [[ -f "$VAULT_FILE" ]]; then
  echo ""
  echo "Vault file already exists at $VAULT_FILE"
  echo "Decrypting to check for existing managed_db vars..."

  EXISTING=$(ansible-vault view "$VAULT_FILE" 2>/dev/null || true)
  if echo "$EXISTING" | grep -q "vault_managed_db_host"; then
    echo "WARNING: vault_managed_db_* vars already exist. Overwrite? [y/N]"
    read -r CONFIRM
    if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
      echo "Aborted."
      exit 0
    fi
  fi

  # Decrypt, append/update, re-encrypt
  TMPFILE=$(mktemp)
  trap 'rm -f "$TMPFILE"' EXIT
  ansible-vault decrypt "$VAULT_FILE" --output "$TMPFILE"

  # Remove existing managed_db lines if present
  sed -i.bak '/^vault_managed_db_/d' "$TMPFILE"
  rm -f "$TMPFILE.bak"

  # Append new values
  cat >> "$TMPFILE" <<VARS

# Managed database credentials (from DigitalOcean)
vault_managed_db_host: "$DB_HOST"
vault_managed_db_user: "$DB_USER"
vault_managed_db_password: "$DB_PASS"
VARS

  ansible-vault encrypt "$TMPFILE" --output "$VAULT_FILE"
  rm -f "$TMPFILE"
  trap - EXIT
else
  echo ""
  echo "Creating new vault file at $VAULT_FILE"
  echo "$VAULT_CONTENT" | ansible-vault encrypt --output "$VAULT_FILE" -
fi

echo ""
echo "Done. Vault file written to: $VAULT_FILE"
echo ""
echo "Verify with:"
echo "  ansible-vault view $VAULT_FILE"
echo ""
echo "Next step — run the migration:"
echo "  ansible-playbook -i ansible/inventory/hosts.yml \\"
echo "    ansible/playbooks/migrate-to-managed-db.yml \\"
echo "    --limit $ENVIRONMENT -e confirm_production=yes"
