---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert role applied successfully
      ansible.builtin.assert:
        that: true
        success_msg: "openlitespeed role applied successfully"
