---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Getent passwd for 'deploy'
      ansible.builtin.getent:
        database: passwd
        key: deploy
      register: getent_passwd
      failed_when: getent_passwd is failed
