---
modsecurity_enabled: true
modsecurity_rule_engine: "DetectionOnly"
modsecurity_pcre_match_limit: 500000
modsecurity_pcre_match_limit_recursion: 500000
modsecurity_request_body_limit: 13107200
modsecurity_request_body_nofiles_limit: 131072
modsecurity_request_body_inmemory_limit: 131072
modsecurity_response_body_limit: 524288
modsecurity_audit_engine: "RelevantOnly"
modsecurity_audit_log: "/var/log/apache2/modsec_audit.log"
modsecurity_tmp_dir: "/var/lib/modsecurity/tmp"
modsecurity_data_dir: "/var/lib/modsecurity/data"
modsecurity_unicode_map_file: "unicode.mapping 20127"
