---
# Cloudflare Role Handlers

- name: Reload Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart cf-purge-watcher
  ansible.builtin.systemd:
    name: cf-purge-watcher
    state: restarted
    daemon_reload: yes
