name: Deploy to Development

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      ansible_limit: dev
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      ANSIBLE_VAULT_FILE: ${{ secrets.ANSIBLE_VAULT_FILE }}
