name: Deploy to Production (New)

on:
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production_new
      ansible_limit: pausatf-prod-new
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.PROD_NEW_SSH_PRIVATE_KEY }}
      TARGET_SERVER_IP: ${{ secrets.PROD_NEW_SERVER_IP }}
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      ANSIBLE_VAULT_FILE: ${{ secrets.ANSIBLE_VAULT_FILE }}
